## Operations

Arithmetic operations on NumPy arrays are applied element wise, and returns a 'NEW' array with results.


In [1]:
import numpy as np

a = np.array([10,20,30,40])
b = a + 1
print(a)
print(b)

c = b - a
print(c)

[10 20 30 40]
[11 21 31 41]
[1 1 1 1]


In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 4])

z = x @ y
print(z)

Some short hand operations like `*=` , `+=` modify the source array in place rather than creating a new one


In [ ]:
a_ones = np.ones((2,3))
print(a_ones)

a_ones += 1
print(a_ones)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
scores = np.array([50,45,30,49,62])
results = scores > 35

print("Pass / Faile ? :", results)
print("Centum", scores == 0)


Pass / Faile ? : [ True  True False  True  True]
Centum [False False False False False]


## Math Operations

- sum
- min
- max
- prod
- cumsum, cumprod
- mean / average, median

for more math operations check [here](https://numpy.org/devdocs/user/quickstart.html#basic-operations)

In [13]:
scores = np.array([1, 2, 3, 4, 5])
total = scores.sum()
print(total)

low = scores.min()
print(low)

high = scores.max()
print(high)

fact = scores.prod()
print(fact)

cum_sum = scores.cumsum()
print(cum_sum)

cum_prod = scores.cumprod()
print(cum_prod)

15
1
5
120
[ 1  3  6 10 15]
[  1   2   6  24 120]
